sulu_product.product_list:
    pattern: /template/product/list.html
    defaults: { _controller: SuluProductBundle:Template:productList }

sulu_product.product_variants:
    pattern: /template/product/variants.html
    defaults: { _controller: SuluProductBundle:Template:productVariants }

sulu_product.product_form:
    pattern: /template/product/form.html
    defaults: { _controller: SuluProductBundle:Template:productForm }

sulu_product.product_import:
    pattern: /template/product/import.html
    defaults: { _controller: SuluProductBundle:Template:productImport }

attribute_list:
    pattern: /template/attribute/list.html
    defaults: { _controller: SuluProductBundle:Template:attributeList }

attribute_form:
    pattern: /template/attribute/form.html
    defaults: { _controller: SuluProductBundle:Template:attributeForm }

sulu_product.product_pricing:
    pattern: /template/product/pricing.html
    defaults: { _controller: SuluProductBundle:Template:productPricing }

sulu_product.product_documents:
    pattern: /template/product/documents.html
    defaults: { _controller: SuluProductBundle:Template:productDocuments }

sulu_product.product_attributes:
    pattern: /template/product/attributes.html
    defaults: { _controller: SuluProductBundle:Template:productAttributes }
